const movieData = [
  {
    id: 1,
    title: " G.O.A.T , Full Movie",
    fileSize: "",
    format: "",
    resolution: "",
    subtitles: [""],
    low: "https://tinyurl.com/243fjwfy",
    mid: "https://tinyurl.com/243fjwfy",
    high: "https://link.pocolinks.com/fhvVduK",
    
  },

  
  {
      // id: 2,
    // title: " Link Not Available",
    // fileSize: "",
    // format: "",
    // resolution: "",
    // subtitles: [""],
    // low: "https://drive.google.com/open?id=1ZvUsrDfCZBvyX6xpzgj70rA_Jib11q0z",
    // mid: "https://drive.google.com/open?id=1ZvUsrDfCZBvyX6xpzgj70rA_Jib11q0z",
    // high: "https://drive.google.com/open?id=1ZvUsrDfCZBvyX6xpzgj70rA_Jib11q0z",
  },

  {
    // id: 3,
    // title: "Maharaja (Hindi Dubbed)",
    // fileSize: "404 MB",
    // format: "MP4",
    // resolution: "720p",
    // subtitles: ["Hindi"],
    // low: "",
    // mid: "",
    // high: "",
  },

  {
    // id: 4,
    // title: "The Family Star (Hindi Dubbed)",
    // fileSize: "917.858 MB",
    // format: "MP4",
    // resolution: "720p",
    // audio: " Mono",
    // subtitles: ["Hindi"],
    // low: "",
    // mid: "",
    // high: "",
  },

  {
    // id: 5,
    // title: "Vicky Vidya Ka Woh Wala Video (Full Movie)",
    // fileSize: "932.343 MB",
    // format: "MP4",
    // resolution: "720p",
    // subtitles: ["Hindi"],
    // low: "https://www.2filmydhoom.com/download/9810/2",
    // mid: "",
    // high: "",
  },

  {
    // id: 6,
    // title: " Link Not Available",
    // fileSize: "454.811 MB",
    // format: "MKV",
    // resolution: "1080p",
    // audio: " 7.1 Surround",
    // subtitles: ["Hindi"],
    // low: "",
    // mid: "",
    // high: "",
  },

  {
    // id: 7,
    // title: "Stree 2 (Full Movie)",
    // fileSize: "946.695 MB",
    // format: "MP4",
    // resolution: "720p",
    // subtitles: ["Hindi"],
    // low: "",
    // mid: "",
    // high: "",
  },

  {
    // id: 8,
    // title: "Salaar(Hindi Dubbed)",
    // fileSize: "1.124 GB",
    // format: "MP4",
    // resolution: "720p",
    // subtitles: ["Hindi"],
    // low: "https://fine-download.com/4a981e0b62f15dabb0cd4b107ff324d7535863d141e9fa309f743db1923167132fef50ec75d1a5bc454f4a66f24944e7dfd0fb29ac6fd966",
    // mid: "",
    // high: "",
  },

  {
    // id: 9,
    // title: "Fight Club",
    // fileSize: "2.3 GB",
    // format: "MP4",
    // resolution: "1080p",
    // subtitles: ["Hindi"],
    // low: "",
    // mid: "",
    // high: "",
  },

  {
    // id: 10,
    // title: "Bad Newz , Full Movie",
    // fileSize: "974.679 MB",
    // format: "MP4",
    // resolution: "720p",
    // subtitles: ["Hindi"],
    // low: "",
    // mid: "",
    // high: "",
  },
];
